### ISSUE TITLE
Consider performing clang-tidy static analysis

### ISSUE THREAD

**Issue by nilssonk** [swedishembedded/control#9]
Hello Martin, I stumbled across your project on linkedin and found it very interesting (especially the presence of a sqrt UKF implementation)! Overall the code quality looks good, but just to be on the safe side I ran a hacked together clang-tidy check which uncovered some ambiguities related to implicit variable casting, use of srand/rand functions and use of Variable-Length Arrays.
Perhaps it would be a good thing to have integrated with the project officially? I could make a PR with initial support if you are interested and then you could take a stance on what checks you want to perform.

Regards,
Kim

**Comment by mkschreder** [comment]
Good point. Definitely a good thing to integrate. Post a PR with your work in progress and we can discuss the best way to add it.

**Comment by mkschreder** [comment]
We can add clang-tidy to https://github.com/swedishembedded/control/blob/main/scripts/check

I also just noticed that there is a few lines duplicated which shouldn't be there. I'll remove the duplicate lines.
